version: "3"
services:
  api:
    build:
      context: ./elevatorrestapp
    volumes:
      - ./elevatorrestapp:/elevatorrestapp
    ports:
      - ${ELEVATOR_MULTITHREADING_BACKEND_PORT}:8080
  ui:
    build:
      context: ./elevator-ui
    environment:
      ELEVATOR_MULTITHREADING_BACKEND_HOST: "${ELEVATOR_MULTITHREADING_BACKEND_HOST}"
    ports:
      - ${ELEVATOR_MULTITHREADING_FRONTEND_PORT}:3000
    depends_on:
      - api
    volumes:
      - ./elevator-ui:/app
      - /app/node_modules
