version: "3"
services:
  api:
    build:
      context: ./elevatorrestapp
    volumes:
      - ./elevatorrestapp:/elevatorrestapp
    ports:
      - ${POLLS_VIEWER_BACKEND_PORT}:8080
  ui:
    build:
      context: ./elevator-ui
    environment:
      POLLS_VIEWER_BACKEND_HOST: "${POLLS_VIEWER_BACKEND_HOST}"
    ports:
      - 80:3000
    depends_on:
      - api
    volumes:
      - ./elevator-ui:/app
      - /app/node_modules
